language: java
deploy:
  provider: heroku
  api_key:
    secure: vporfyga/DM470k+KeI6N1w7xG+LictJj/rn2cP3LIXal+4gcN4xd3UXdnLYwNpYzJuXJw1ueE1FR2ZBv5IyLMgK17chT7CGg3vSg6IfDZo+0dOqCTQCLwPOZlOczL972cFITfhmPyxsOylZOGeEvjJC6K2K3JQAsuphRP4dWATubfG+siMZracoJmfqvZaKXLkO4Pl5DruszcxPXDUbRGS8esmjLJPbdePoVXZK6X8/7wgnpTLhSU4uY9+80eebwns1qIhSCYvTp49wg84Cf7XqyuXhR2OGT6RSnzgFAMSSsgjNg6fVJlBQiMbvAPtGi53dbAWYvXL5wOOPg03CZVc15vp10xygT7qiZzNns5CkfO1YDB8frqC89+RyFzyY2c4We1mHK5tq/Fi2sIRyPRI+qjdJrfUW786K7LgKFSLWfYPYeVof3/gwi61iwwOU2FIddzwwRNwAX7PaOhJDqm0qd/qca1BFRGF7LLLMjp/7CD9XgYSqujV/i+dFY1OAMEVh3mIqwrcHMjKJViWsTsVZTIWPmIOORX4K7IWDJ+kDFfkcYhLPcItivHIWFTyeFTk54lFB4QtSK1htZCxdCG2JZQui/tDRf0tvEQQrdGoHJNXI9QMt2a5lrinUaTYwt29TDDVI02z1YljkNOodd/2QlICyCZm5UywFXDkUNdU=
  app: lightrip-server
